export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_ACTIVITIES_REQUEST = 'FETCH_ACTIVITIES_REQUEST';
export const FETCH_ACTIVITIES_ERROR = 'FETCH_ACTIVITIES_ERROR';
export const SET_ACTIVITIES = 'SET_ACTIVITIES';
